version: "3"
services: 
  react-app:
    image: pfsys-container
    stdin_open: true
    ports:
      - "3001:3000"
    volumes:
      - "./:/app:delegated"
      - /app/node_modules/
  
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #    size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
