version: "3.8"
networks:
  laravel:
    driver: bridge
    ipam:
      config: 
        - subnet: 172.16.238.0/24
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80" # binds local 8081 port with nignx's 80 port
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - laravel
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3307:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: database
    networks: 
      - laravel
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
    networks: 
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
        - ./src:/var/www/html
    ports:
        - "9000:9000"
    networks: 
      - laravel
  composer:
    container_name: composer
    image: composer:latest
    command: ["composer", "install"]
    depends_on: 
      - php
    volumes:
      - ./src/code:/app
    restart: always
    networks: 
      - laravel